# Generated by Django 5.0.4 on 2024-05-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(choices=[('DR', 'انتقاد'), ('PB', 'پیشنهاد'), ('RJ', 'گزارش')], default='DR', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'در انتظار'), ('PB', 'منتشر شده'), ('RJ', 'رد شده')], default='DR', max_length=2),
        ),
    ]
