# Generated by Django 5.0.4 on 2024-05-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='shop_image_created_6a3b1a_idx'),
        ),
    ]
