# Generated by Django 5.0.4 on 2024-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_post_inventory_post_off_alter_post_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت پس از تخفیف'),
        ),
    ]
