# Generated by Django 5.0.6 on 2024-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_post_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن'),
        ),
    ]
