# Generated by Django 5.0.6 on 2024-07-19 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_post_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام ویژگی')),
                ('value', models.CharField(max_length=250, verbose_name='مقدار ویژگی')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='weight',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f_products', to='shop.productfeature', verbose_name='ویژگیها'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='shop_post_title_2f57fb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id', 'slug'], name='shop_post_id_416257_idx'),
        ),
    ]
