# Generated by Django 5.0.6 on 2024-07-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_post_feature_delete_productfeature'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='shop_post_title_2f57fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='shop_post_id_416257_idx',
        ),
    ]
