# Generated by Django 5.0.6 on 2024-07-19 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_post_shop_post_title_2f57fb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ویژگی')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id', 'slug'], name='shop_post_id_416257_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='shop_post_title_2f57fb_idx'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.post', verbose_name='محصول'),
        ),
    ]
