# Generated by Django 5.0.6 on 2024-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن'),
        ),
    ]
